# Jekyll Configuration
title: "Vladimir Iliev - CV"
description: "Personal CV website with multi-language support"

baseurl: "/web-cv--jekyll"
url: "https://vladko-iliev.github.io"

# Build settings
markdown: kramdown
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
