title: Vladimir Iliev - CV
description: Personal CV website with multi-language support
baseurl: "/web-cv--jekyll"
url: "https://vladko-iliev.github.io"

# Theme Settings
remote_theme: sharu725/online-cv
skin: blue

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme